### ISSUE TITLE
Adopt ASL 2.0 license.

### ISSUE THREAD

**Issue by jdcasey** [Commonjava/atlas#25]
@douglaspalmer @pkocandr @janinko I'd like to change the license on this project to ASL 2.0 to make it easier to use in other projects. I'm still trying to understand the implications of depending on neo4j (GPL) for this process.

But, you are all contributors to this codebase. Are you okay with the change?

**Comment by pkocandr** [comment]
Yep, no problem with that.

**Comment by sbadakhc** [comment]
Sweet!

**Comment by janinko** [comment]
I don't know how much I contributed by deleting 2 lines, but I agree :D
