### ISSUE TITLE
SimpleProjectRef/SimpleProjectVersionRef

### ISSUE THREAD

**Issue by rnc** [Commonjava/atlas#42]
SimpleProjectRef uses isEmpty to check group / artifact. SimpleProjectVersionRef uses null (rather than isEmpty) to check version - this seems inconsistent?

**Comment by rnc** [comment]
Found during looking at https://github.com/release-engineering/pom-manipulation-ext/issues/221

**Comment by jdcasey** [comment]
fixed in https://github.com/Commonjava/atlas/pull/43
